"""Markdown report renderer.

Renders findings as GitHub-flavored Markdown -- the format that drops straight into
a pull-request comment, a GitHub issue, a Slack message, or a job summary. It leads
with a one-line headline (totals, severity breakdown, and how many findings are
known-exploited), a compact severity table, and a prioritized findings table
carrying the composite risk score, CVSS, EPSS, and a KEV marker.

Like the other reporters it is pure and **deterministic for fixed input**: findings
are emitted in the order given (the prioritized order), severities appear in a fixed
worst-to-least order, and no wall-clock timestamp is embedded. Table cells are
escaped so a pipe or newline in scanner evidence can never break the table layout.
"""

from collections.abc import Iterable

from vulnpipe import __version__
from vulnpipe.core.models import Finding, Severity
from vulnpipe.reporting.base import BaseReporter
from vulnpipe.reporting.summary import SEVERITY_DISPLAY_ORDER, ReportSummary, summarize

_TITLE = "vulnpipe security report"

#: Per-severity Markdown label: a colored dot (matching the HTML palette) plus a
#: word, so a rendered report is scannable at a glance on GitHub or Slack.
_SEVERITY_LABEL: dict[Severity, str] = {
    Severity.CRITICAL: "🟣 Critical",
    Severity.HIGH: "🔴 High",
    Severity.MEDIUM: "🟠 Medium",
    Severity.LOW: "🟡 Low",
    Severity.INFORMATIONAL: "🔵 Info",
}


def _escape_cell(value: str) -> str:
    """Make ``value`` safe inside a Markdown table cell (no layout-breaking chars)."""
    return " ".join(value.split()).replace("\\", "\\\\").replace("|", "\\|")


def _format_cvss(score: float | None) -> str:
    return f"{score:.1f}" if score is not None else "—"


def _format_epss(score: float | None) -> str:
    return f"{score * 100:.1f}%" if score is not None else "—"


def _host_label(finding: Finding) -> str:
    return finding.host if finding.port is None else f"{finding.host}:{finding.port}"


def _summary_line(summary: ReportSummary, kev_count: int) -> str:
    hosts = "host" if summary.host_count == 1 else "hosts"
    breakdown = ", ".join(
        f"{summary.by_severity[severity]} {severity.value}" for severity in SEVERITY_DISPLAY_ORDER
    )
    line = f"**{summary.total} findings across {summary.host_count} {hosts}** — {breakdown}"
    if kev_count:
        line += f" · ⚠️ **{kev_count} known-exploited (KEV)**"
    return line


def _severity_table(summary: ReportSummary) -> list[str]:
    rows = ["| Severity | Count |", "| --- | ---: |"]
    for severity in SEVERITY_DISPLAY_ORDER:
        rows.append(f"| {_SEVERITY_LABEL[severity]} | {summary.by_severity[severity]} |")
    return rows


def _findings_table(findings: list[Finding]) -> list[str]:
    rows = [
        "| # | Severity | Risk | Source | Host | Finding | CVSS | EPSS | Exploited |",
        "| ---: | --- | ---: | --- | --- | --- | ---: | ---: | :---: |",
    ]
    for index, finding in enumerate(findings, start=1):
        exploited = "⚠️ **Yes**" if finding.kev else "—"
        rows.append(
            f"| {index} "
            f"| {_SEVERITY_LABEL[finding.severity]} "
            f"| {finding.risk_score} "
            f"| {_escape_cell(finding.source)} "
            f"| {_escape_cell(_host_label(finding))} "
            f"| {_escape_cell(finding.title)} "
            f"| {_format_cvss(finding.cvss_score)} "
            f"| {_format_epss(finding.epss_score)} "
            f"| {exploited} |"
        )
    return rows


def render_markdown(findings: Iterable[Finding]) -> str:
    """Render ``findings`` into a GitHub-flavored Markdown report string."""
    items = list(findings)
    summary = summarize(items)
    kev_count = sum(1 for finding in items if finding.kev)

    lines = [f"# {_TITLE}", "", _summary_line(summary, kev_count), "", "## Severity summary", ""]
    lines.extend(_severity_table(summary))
    lines.extend(["", "## Findings", ""])
    if items:
        lines.extend(_findings_table(items))
    else:
        lines.append("_No findings._")
    footer = f"<sub>Generated by vulnpipe {__version__} — detection & reporting only.</sub>"
    lines.extend(["", footer])
    return "\n".join(lines) + "\n"


class MarkdownReporter(BaseReporter):
    """Render findings into a deterministic GitHub-flavored Markdown report."""

    name = "markdown"

    def render(self, findings: list[Finding]) -> str:
        return render_markdown(findings)


__all__ = [
    "MarkdownReporter",
    "render_markdown",
]
